# Generated by Django 2.1.3 on 2018-11-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ContactLens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clens', models.CharField(max_length=32)),
                ('num_year_supply', models.IntegerField()),
                ('cost_per_package', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.AddField(
            model_name='contactattribute',
            name='clenses',
            field=models.ManyToManyField(to='cl.ContactLens'),
        ),
    ]
