# Generated by Django 2.1.3 on 2018-11-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRebate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=64)),
                ('from_dt', models.DateField()),
                ('to_dt', models.DateField()),
                ('amt', models.DecimalField(decimal_places=2, max_digits=7)),
                ('lenses', models.ManyToManyField(to='cl.ContactLens')),
            ],
        ),
    ]
