# Generated by Django 2.1.3 on 2018-11-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0002_contactrebate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrebate',
            name='exclusive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactrebate',
            name='half_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
