# Generated by Django 2.1.3 on 2018-11-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0003_auto_20181111_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlens',
            name='clens',
            field=models.CharField(max_length=128),
        ),
    ]
