# Generated by Django 2.1.3 on 2018-11-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0004_auto_20181112_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDefaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('def_cl_service_amt', models.DecimalField(decimal_places=2, max_digits=7)),
                ('def_exam_amt', models.DecimalField(decimal_places=2, max_digits=7)),
                ('def_benefit_amt', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactattribute',
            options={'ordering': ['attribute']},
        ),
        migrations.AlterModelOptions(
            name='contactlens',
            options={'ordering': ['clens'], 'verbose_name_plural': 'Contact lenses'},
        ),
        migrations.AlterModelOptions(
            name='contactrebate',
            options={'ordering': ['-to_dt']},
        ),
    ]
