# Generated by Django 2.1.3 on 2018-11-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0006_auto_20181125_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlens',
            name='power_ranges',
        ),
    ]
