# Generated by Django 2.1.3 on 2018-11-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0007_remove_contactlens_power_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlens',
            name='power_ranges',
            field=models.TextField(blank=True),
        ),
    ]
