# Generated by Django 2.1.3 on 2018-12-01 22:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl', '0009_remove_contactlens_power_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='configdefaults',
            name='def_ys_discount',
            field=models.DecimalField(decimal_places=1, default=Decimal('20'), max_digits=3),
        ),
    ]
